In [1]:
import numpy as np

vector = np.array([1,2,3])
print(vector)
print("")

mat = np.array([[1,2,3],[1,3,3]])
print(mat)
print("")

vec2 = np.arange(0, 20, 4)
vec3 = np.linspace(0, 30, 3)
print(vec2)
print(vec3)
print("")

tempArray = [2, 4, 6, 8]
print(tempArray)

# Convert array to matrtix
print(vec3.reshape(3, 1))

[1 2 3]

[[1 2 3]
 [1 3 3]]

[ 0  4  8 12 16]
[ 0. 15. 30.]

[2, 4, 6, 8]
[[ 0.]
 [15.]
 [30.]]


In [10]:
matrixOne = np.array([range(0,5), range(5, 10)])
m = np.matrix([range(0,5), range(5, 10)])
print(m * m.getT())

[[ 30  80]
 [ 80 255]]


In [18]:
print(np.arange(0, 12).reshape(4, 3))
print([1, True, "Hi"])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[1, True, 'Hi']


In [20]:
np.cos(np.pi)
np.sqrt(1.44)
np.log(6)
np.exp(4)

54.598150033144236

In [21]:
print(np.arange(4, 20, 5))

[ 4  9 14 19]


In [23]:
print(np.arange(10, 20)[np.arange(0, 10, 3)])

[10 13 16 19]


In [27]:
array1 = np.array([range(0,5), range(5, 10)])
array2 = array1

print(array1)

array2 = array1 * array1

print("")
print(array1)

print("")
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[ 0  1  4  9 16]
 [25 36 49 64 81]]


In [29]:
matrixOne = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrixOne)
print(matrixOne[1, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


In [34]:
vec = np.array([4, 7, 8, 9, 10, 6, 1])
print(vec[vec>6])

[ 7  8  9 10]


In [48]:
import pandas as pd

score = [10, 15, 20, 25]

print(pd.Series(data=score, index = ['a','b','c','d']))

a    10
b    15
c    20
d    25
dtype: int64


In [50]:
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])
newColumn = [2, 2, 2]
df2['c'] = newColumn
print(df2)

   a  b  c
0  1  2  2
1  4  5  2
2  7  8  2


In [52]:
print(np.arange(0, 22, 6))

[ 0  6 12 18]


In [53]:
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

print(subset_demo_array)

[101 101 101 101 101 101 101]


In [55]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

print(flowers['daisy'])
print(df2.drop('c', axis=1))

5
   a  b
0  1  2
1  4  5
2  7  8


In [62]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])
print(pd.concat([s1,s2]))

0    a
1    b
0    c
1    d
dtype: object
